spring.datasource.url=mysql://containers-us-west-123.railway.app:6543/railway
spring.datasource.username=root
spring.datasource.password=Riddhi@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
